apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    failure-domain.beta.kubernetes.io/zone: us-west1-b
spec:
  capacity: 
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4