apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes/hostname
          operator: In
          values:
          - node-selector-db