apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: default
spec:
  storageClassName: ""
  volumeName: mysql-pv-volume
  resources:
    requests:
      storage: 10Gi # min size on gc ssd https://cloud.google.com/compute/docs/disks