bases:
- ../../base/deploy/
patchesStrategicMerge:
- storage-overlays/stateful-set-patch.yaml
- api-config-map-patch.yaml
resources:
- persistent-volume-claim.yaml
- persistent-volume.yaml
namePrefix: development-