apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db-stateful-set
spec:
  serviceName: "db-service"
  selector:
    matchLabels:
      app: db # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - image: mysql:8.0.19
        name: db-container
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: ctodo
        - name: MYSQL_ROOT_PASSWORD
          value: example
        livenessProbe:
          tcpSocket:
            port: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      # Make sure and set Volumes in patch, dif requirements per provider